### ISSUE TITLE
有论文的链接吗

### ISSUE THREAD

**Issue by kalpa61** [likemby/EDMDBN#1]

**Comment by likemby** [comment]
暂时还没有，等论文接收了再公开

**Comment by kalpa61** [comment]
SMIC数据集没有起始帧和峰值帧等标注信息，可以说下你是如何获取峰值帧索引的吗？非常感谢 @likemby

**Comment by likemby** [comment]
简单取中间帧即可



---- 回复的原邮件 ----
| 发件人 | BingYu ***@***.***> |
| 日期 | 2024年11月14日 19:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [likemby/EDMDBN] 有论文的链接吗 (Issue #1) |

SMIC数据集没有起始帧和峰值帧等标注信息，可以说下你是如何获取峰值帧索引的吗？非常感谢 @likemby

**Comment by kalpa61** [comment]
ok,感谢
